### ISSUE TITLE
[C#] Realtime Progress bar legendary winform

### ISSUE THREAD

**Issue by Soi9x** [suchmememanyskill/Legendary-GUI#5]
Hi , I need help with printing % progress bar from the time the app launches the command line to the end of the process with the messagebox message, I need help, contact me at gmail vnsoixam9x@gmail.com. com , I have come across your project the code is very complex , I want simpler

**Comment by suchmememanyskill** [comment]
Hi, i don't support the winforms version anymore (v1, which are the LegendaryMapper and LegendaryGUI components in this repo). It has been superseeded by v2, which runs on avalonia to be cross platform. This works a lot like wpf.

I'm willing to explain the code, but on my own accord. [I have a discord that i use for development, feel free to ask any questions there](https://discord.gg/aH9rsuP)

**Comment by Soi9x** [comment]
hi , where is your discord channel !

**Comment by suchmememanyskill** [comment]
It is posted as a hyperlink in github. I'm unsure if you can see this in an email. To be sure, here is the full link: [https://discord.gg/aH9rsuP](https://discord.gg/aH9rsuP)

**Comment by Soi9x** [comment]
Awesome, thanks! , MyID: Discord Username Me : SoiXam9x#4318 , the number
of people participating in discord is too much how can i tag you

**Comment by suchmememanyskill** [comment]
? My server is public and has no restrictions. Do you mean you don't want to join the server or you cannot join the server? (If the latter, are you in 100 servers by chance? I think discord does not let you join more than 100 servers)
